# Generated by Django 2.1.7 on 2019-03-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190228_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyemployee',
            name='endDatetime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='surveyemployee',
            name='startDatetime',
            field=models.DateField(),
        ),
    ]
