# Generated by Django 2.1.7 on 2019-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20190306_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyemployee',
            name='flag',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
