# Generated by Django 2.1.7 on 2019-03-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_surveyemployee_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyemployee',
            name='flag',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
