# Generated by Django 2.1.7 on 2019-03-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20190308_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_password',
        ),
    ]
