# Generated by Django 2.1.7 on 2019-03-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_remove_employee_emp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
