# Generated by Django 2.1.7 on 2019-03-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_employee_emp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyemployee',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='surveyemployee',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='surveyemployee',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='date',
        ),
        migrations.AddField(
            model_name='survey',
            name='employee',
            field=models.ManyToManyField(to='survey.Employee'),
        ),
        migrations.AddField(
            model_name='survey',
            name='endDatetime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='flag',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='question',
            field=models.ManyToManyField(to='survey.Question'),
        ),
        migrations.AddField(
            model_name='survey',
            name='startDatetime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SurveyEmployee',
        ),
        migrations.DeleteModel(
            name='SurveyQuestion',
        ),
    ]
