# Generated by Django 2.1.7 on 2019-03-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20190319_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
